### ISSUE TITLE
[Enhancement] Improve error messages

### ISSUE THREAD

**Issue by moritzkirstein** [deltaDAO/portal-safeFBDC#23]
## Motivation / Problem
Error messages are not really useful to the user. See access denied because of asset whitelists as an example below:

When logged in with an account that is not on whitelist the `use` section does not indicate any restrictions. There is no message for the user before buying, that access is not granted / account is not found on whitelist:

![grafik](https://user-images.githubusercontent.com/28757404/152429970-190a9a6d-7711-453c-b17e-7d358663f771.png)

User is then able to buy datatokens (this is wanted behaviour - at least for ocean market) but the error message does not give any information as to why the compute job could not be started:

![grafik](https://user-images.githubusercontent.com/28757404/152430378-4f571f64-ad1c-40ef-8d76-c5baaf64d61d.png)

## Solution 
- Provide information for user that access is restricted (maybe alert before buying or similar)
- Improve error messages

## Alternatives
Any alternatives are welcome to be discussed in this issue.

**Comment by LucaMilanese90** [comment]
@moritzkirstein I was thinking of putting a short warning right before the "buy compute job" button (the actual message is up for debate)
<img width="447" alt="Screenshot 2022-02-04 at 15 42 09" src="https://user-images.githubusercontent.com/20192135/152550579-a6f835c2-2afe-4b6f-bf65-d30961fdc5e0.png">
And if the user decides to still try to start the job the error message will remind him why it's not working
<img width="505" alt="Screenshot 2022-02-04 at 15 53 13" src="https://user-images.githubusercontent.com/20192135/152550777-a33977df-2f57-405c-bc5a-cb713706db1d.png">

Do you think the first warning should be more prominent (maybe a colored box or a bigger font size)?

**Comment by moritzkirstein** [comment]
I like the idea. Maybe let's use the alert component here and use a warning alert.

*Warning:*
Your account is not authorized to access this data service.

**Comment by LucaMilanese90** [comment]
Better?

<img width="481" alt="Screenshot 2022-02-04 at 16 14 19" src="https://user-images.githubusercontent.com/20192135/152553589-994fff63-dd60-476e-ba48-26677680106b.png">
